conda_forge_output_validation: true
os_version:
  linux_64: cos7
  linux_aarch64: cos7
  linux_ppc64le: cos7
provider:
  linux_aarch64: default
  linux_ppc64le: default
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
azure:
  free_disk_space: True
